### ISSUE TITLE
Conf ovpn not updated

### ISSUE THREAD

**Issue by michael1900** [cryptostorm/cryptostorm_client_configuration_files#17]
With cstorm widget i see more updated ovpn that are not present in the last github like for example voodoo connections:

denmark-isleofman
italy-romania
romania-russia
obfsproxy-romania

This is a big problem for macuser, because there is not a mac client unfortunately

And i don't know if there are others not updated.
Where the widget takes and saves .ovpn when we update them from it? 
From which link widget download every ovpn conf?

Is it possible to update conf also here on github?

**Comment by df-cryptostorm** [comment]
Updated
