### ISSUE TITLE
.ovpn files using a deprecated option

### ISSUE THREAD

**Issue by xse** [cryptostorm/cryptostorm_client_configuration_files#18]
Hi, 
As of openvpn 2.4.0, "ns-cert-type server" is deprecated and should instead be:
"remote-cert-tls server"
When using the cryptofree .ovpn file i get a warning : 

> Mon Oct  2 22:32:11 2017 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.

I tested the configuration with the "remote-cert-tls server" line and all is working great !
It might be a good idea to update all thoses .ovpn files since the stable version of openvpn is now 2.4.4.

Keep up the good work !

**Comment by df-cryptostorm** [comment]
A lot of our customers are using these configs on embedded devices (routers, etc.) where it's sometimes difficult to update to the latest OpenVPN. So for now, at least until that deprecated warning becomes a fatal error, we'll leave it as is.
