### ISSUE TITLE
Add instructions for NetworkManager Applet

### ISSUE THREAD

**Issue by baimafeima** [cryptostorm/cryptostorm_client_configuration_files#21]
Could you please add instructions on how to use Cryptostorm via `NetworkManager Applet`, the notification area applet which comes pre-installed in Solus, the operating system of my choice? I went to your website but only found a short notice that it should be found on the forums but these I couldn't find. Thank you.

**Comment by whoamipl** [comment]
You need to choose import saved vpn setting, and that's all. What os do you ues. I've meet some problems in use it that way on Debian. But in Ubuntu, Manjaro and Arch there is no problem.

**Comment by whoamipl** [comment]
https://torguard.net/knowledgebase.php?action=displayarticle&id=53 you can do this as described in above articke, but for username you must use hash of your cryptostorm token, and fill password input with some random password.

**Comment by whoamipl** [comment]
Sorry, but I've missed that you've mentioned which os you use.

**Comment by baimafeima** [comment]
I use Solus (https://solus-project.com/) and am a rather non-technical user.

**Comment by baimafeima** [comment]
I cannot access the link you've mentioned from China but your website opens up just fine. Would be great to add instructions there or here on GitHub in case your website will get censored. That being said, I am not even sure if it will actually work in China. The only way for me it seems is to obfuscate the traffic. Do you have anything planned? Like a native Linux client? openVPN cannot be used anymore in many regions unless it is patched with Tunnelblick (ECC/XOR) or obfs4 or has stunnel integrated. Would be really great to see basic instructions on your website and a new Linux client.

**Comment by df-cryptostorm** [comment]
Network Manager instructions are at https://cryptostorm.is/nix#netman
