### ISSUE TITLE
ca.crt on Mac

### ISSUE THREAD

**Issue by LuisMAntunes** [cryptostorm/cryptostorm_client_configuration_files#3]
Getting the following error while trying to configure this on Mac:

> Installation failed:
> At line 25 of the OpenVPN configuration file: The configuration file refers to a file
> ca.crt
> which should be located at
> ~/Downloads/cryptostorm_client_configuration_files-master 2/linux/ca.crt
> but the file does not exist.

**Comment by df-cryptostorm** [comment]
All the Linux configs use inline data for the CA file, but if your setup is complaining about that then just open up the config and copy everything between `<ca>` and `</ca>` and paste it into ~/Downloads/cryptostorm_client_configuration_files-master 2/linux/ca.crt
